import test from 'node:test';
import assert from 'node:assert/strict';
import { isOwnerEmail, isSameOrigin, validateDraft, validateAction } from '../lib/article-workflow.ts';

const article = (status = 'pending', revision = 1) => ({ status, revision });
const draft = () => ({ title: 'A practical network plan', body: 'Plan your home and shed connectivity with VINCONNECT.' });

test('owner email grants access only to configured exact address', () => assert.equal(isOwnerEmail('destefano.vince1@gmail.com'), true));
test('another signed-in account cannot access owner workspace', () => assert.equal(isOwnerEmail('other@gmail.com'), false));
test('missing email cannot access owner workspace', () => { for (const email of [null, undefined, '', 1, {}]) assert.equal(isOwnerEmail(email), false); });
test('owner substring does not grant access', () => assert.equal(isOwnerEmail('destefano.vince1@gmail.com.evil.test'), false));
test('same origin accepts a nested request path', () => assert.equal(isSameOrigin('https://hub.test/api/articles', 'https://hub.test'), true));
test('absent and opaque origins fail closed', () => { for (const origin of [null, '', 'null']) assert.equal(isSameOrigin('https://hub.test/api/articles', origin), false); });
test('cross origin request rejected', () => assert.equal(isSameOrigin('https://hub.test/api/articles', 'https://evil.test'), false));
test('different port rejected', () => assert.equal(isSameOrigin('https://hub.test/api/articles', 'https://hub.test:8443'), false));
test('different scheme rejected', () => assert.equal(isSameOrigin('https://hub.test/api/articles', 'http://hub.test'), false));
test('malformed origin rejected without throwing', () => assert.equal(isSameOrigin('https://hub.test/api/articles', 'invalid origin'), false));
test('credential-bearing origin rejected', () => assert.equal(isSameOrigin('https://hub.test/api/articles', 'https://user:pass@hub.test'), false));
test('non-http origin rejected', () => assert.equal(isSameOrigin('file:///api/articles', 'file:///'), false));
test('origin with unexpected path or query rejected', () => { for (const origin of ['https://hub.test/path', 'https://hub.test?q=1', 'https://hub.test#x']) assert.equal(isSameOrigin('https://hub.test/api/articles', origin), false); });
test('valid article preserves text', () => assert.deepEqual(validateDraft(draft()), draft()));
test('null array and primitive drafts rejected', () => { for (const value of [null, undefined, [], 'x', 4]) assert.throws(() => validateDraft(value)); });
test('missing fields rejected', () => { assert.throws(() => validateDraft({ title: 'Title' })); assert.throws(() => validateDraft({ body: draft().body })); });
test('title whitespace cannot meet minimum length', () => assert.throws(() => validateDraft({ ...draft(), title: '   ' })));
test('title over limit rejected', () => assert.throws(() => validateDraft({ ...draft(), title: 'a'.repeat(181) })));
test('short body rejected', () => assert.throws(() => validateDraft({ ...draft(), body: 'Too short' })));
test('body over limit rejected', () => assert.throws(() => validateDraft({ ...draft(), body: 'a'.repeat(20001) })));
test('boundary lengths accepted', () => assert.doesNotThrow(() => validateDraft({ title: 'abc', body: 'a'.repeat(20) })));
test('maximum lengths accepted', () => assert.doesNotThrow(() => validateDraft({ title: 'a'.repeat(180), body: 'a'.repeat(20000) })));
test('HTML-looking input remains plain text data', () => { const value = { title: '<script>alert(1)</script>', body: '<img src=x onerror=alert(1)> & "quoted"' }; assert.deepEqual(validateDraft(value), value); });
test('pending article can save', () => assert.doesNotThrow(() => validateAction(article(), 'save', 1)));
test('pending article can approve', () => assert.doesNotThrow(() => validateAction(article(), 'approve', 1)));
test('approved article can return to pending', () => assert.doesNotThrow(() => validateAction(article('approved'), 'pending', 1)));
test('approved article can publish', () => assert.doesNotThrow(() => validateAction(article('approved'), 'publish', 1)));
test('approved article can save; caller must reset approval after edits', () => assert.doesNotThrow(() => validateAction(article('approved'), 'save', 1)));
test('pending article cannot publish', () => assert.throws(() => validateAction(article(), 'publish', 1), /Approve/));
test('already approved article cannot approve again', () => assert.throws(() => validateAction(article('approved'), 'approve', 1)));
test('pending article cannot return to pending again', () => assert.throws(() => validateAction(article(), 'pending', 1)));
test('published article rejects all mutation actions', () => { for (const action of ['save', 'approve', 'pending', 'publish']) assert.throws(() => validateAction(article('published'), action, 1)); });
test('stale browser revision rejected', () => assert.throws(() => validateAction(article('pending', 2), 'save', 1), /changed/));
test('future browser revision rejected', () => assert.throws(() => validateAction(article(), 'save', 2), /changed/));
test('zero starting revision accepted', () => assert.doesNotThrow(() => validateAction(article('pending', 0), 'save', 0)));
test('missing nonnumeric fractional negative revisions rejected', () => { for (const revision of [undefined, null, '1', NaN, Infinity, 1.5, -1]) assert.throws(() => validateAction(article(), 'save', revision)); });
test('missing article rejected', () => assert.throws(() => validateAction(null, 'save', 1), /not found/));
test('invalid stored status rejected', () => assert.throws(() => validateAction(article('unknown'), 'save', 1), /status/));
test('invalid stored revision rejected', () => assert.throws(() => validateAction(article('pending', -1), 'save', 1), /stored revision/));
test('unknown actions rejected', () => { for (const action of ['', undefined, 'delete', {}, 1]) assert.throws(() => validateAction(article(), action, 1)); });

test('business email is explicitly authorised',()=>assert.equal(isOwnerEmail('vince@vinconnect.com.au'),true));
test('another business-domain account is not automatically authorised',()=>assert.equal(isOwnerEmail('other@vinconnect.com.au'),false));
test('business email lookalike is rejected',()=>assert.equal(isOwnerEmail('vince@vinconnect.com.au.evil.test'),false));
