import {test,beforeEach} from "node:test";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {registerHooks} from "node:module";
import {readFileSync,existsSync} from "node:fs";
import {fileURLToPath} from "node:url";
let sqlite;
globalThis.__hubTest={user:null,db:null};
const hooks=registerHooks({
 resolve(s,c,next){
  if(s==="cloudflare:workers")return {url:"test:cloudflare",shortCircuit:true};
  if(s.endsWith("chatgpt-auth"))return {url:"test:auth",shortCircuit:true};
  if((s.startsWith(".")||s.startsWith("/"))&&c.parentURL){const u=new URL(s+".ts",c.parentURL);if(u.protocol==="file:"&&existsSync(fileURLToPath(u)))return next(u.href,c);}
  return next(s,c);
 },
 load(u,c,next){
  if(u==="test:cloudflare")return {format:"module",source:"export const env={get DB(){return globalThis.__hubTest.db},get BUCKET(){return globalThis.__hubTest.bucket},get HUB_ENCRYPTION_KEY(){return globalThis.__hubTest.key}}",shortCircuit:true};
  if(u==="test:auth")return {format:"module",source:"export async function getChatGPTUser(){return globalThis.__hubTest.user}",shortCircuit:true};
  return next(u,c);
 }
});
const {GET,POST}=await import("../app/api/articles/route.ts");
const connections=await import("../app/api/connections/route.ts");
const social=await import("../app/api/social/route.ts");
const installations=await import('../app/api/installations/route.ts');
const uploads=await import('../app/api/uploads/route.ts');
const media=await import('../app/media/[id]/route.ts');
const manage=await import("../app/api/articles/manage/route.ts");
let sends=0;let failSend=false;
beforeEach(()=>{
 sqlite?.close();sqlite=new DatabaseSync(":memory:");
 sqlite.exec(readFileSync(new URL("../drizzle/0000_superb_hawkeye.sql",import.meta.url),"utf8"));
 sqlite.exec(readFileSync(new URL("../drizzle/0001_last_lady_mastermind.sql",import.meta.url),"utf8"));
 sqlite.exec(readFileSync(new URL("../drizzle/0002_third_forge.sql",import.meta.url),"utf8"));
 sqlite.exec(readFileSync(new URL("../drizzle/0003_outgoing_yellowjacket.sql",import.meta.url),"utf8"));
 const db={prepare(sql){let args=[];return {bind(...values){args=values;return this},async first(){return sqlite.prepare(sql).get(...args)||null},async all(){return {results:sqlite.prepare(sql).all(...args)}},async run(){const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}}}}},async batch(statements){sqlite.exec("BEGIN");try{const r=await Promise.all(statements.map(s=>s.run()));sqlite.exec("COMMIT");return r}catch(e){sqlite.exec("ROLLBACK");throw e}}};
 globalThis.__hubTest={user:{email:"destefano.vince1@gmail.com",userId:"test-owner"},db,key:Buffer.alloc(32,7).toString("base64")};
 const objects=new Map();globalThis.__hubTest.bucket={async put(id,data){objects.set(id,data)},async get(id){return objects.has(id)?{body:objects.get(id)}:null},async delete(id){objects.delete(id)}};
 sends=0;failSend=false;globalThis.fetch=async(url,opts)=>{assert.equal(opts.redirect,"manual");if(String(url).includes("mcp.windsor.ai")){const input=JSON.parse(opts.body);if(input.method==="initialize")return Response.json({jsonrpc:"2.0",id:1,result:{protocolVersion:"2025-03-26"}});if(input.method==="notifications/initialized")return new Response(null,{status:202});if(input.params?.name==="list_actions")return Response.json({jsonrpc:"2.0",id:2,result:{content:[{type:"text",text:JSON.stringify([{id:input.params.arguments.connector==="instagram"?"create_image_post":"create_photo_post",schema:{properties:{image_url:{type:"string"},caption:{type:"string"}}}}])}]}});if(input.params?.name==="execute_action"){sends++;if(failSend)throw Error("timeout");assert.ok(input.params.arguments.params.image_url.endsWith('.jpg'));return Response.json({jsonrpc:"2.0",id:2,result:{content:[{type:"text",text:JSON.stringify({result:"Photo published successfully. Post ID: 123"})}]}});}return Response.json({jsonrpc:"2.0",id:2,result:{content:[{type:"text",text:JSON.stringify([{id:"facebook_organic",accounts:[{id:"1053341001203753",name:"Vinconnect"}],actions:["create_photo_post"]},{id:"instagram",accounts:[{id:"17841427011293034",name:"vinconnectsolutions"}],actions:["create_image_post"]}])}]}});}if(opts.method==="POST"){sends++;if(failSend)throw Error("timeout");return Response.json({result:"Photo published successfully. Post ID: 123"});}if(String(url).includes("ds-accounts"))return Response.json([{account_id:"1053341001203753",account_name:"Vinconnect",status:"active"},{account_id:"17841427011293034",account_name:"vinconnectsolutions",status:"active"}]);return Response.json([{id:String(url).includes("instagram")?"create_image_post":"create_photo_post"}]);};
});
async function seed(){return (await (await GET()).json()).articles}
const id="vinconnect-article-01";
async function send(input,origin="https://hub.example"){return POST(new Request("https://hub.example/api/articles",{method:"POST",headers:origin?{"Origin":origin,"Content-Type":"application/json"}:{"Content-Type":"application/json"},body:JSON.stringify(input)}));}

async function req(handler,body,origin="https://hub.example"){return handler(new Request("https://hub.example/api/connections",{method:"POST",headers:{Origin:origin},body:JSON.stringify(body)}));}
async function setup(){await seed();await send({id,action:"approve",revision:0});return req(connections.POST,{apiKey:"test-windsor-secret"});}
test("no key reports unconfigured",async()=>{assert.equal((await (await connections.GET()).json()).configured,false)});
test("owner key saves encrypted and is never returned",async()=>{const r=await setup();assert.equal(r.status,200);assert.ok(!JSON.stringify(await r.json()).includes("test-windsor-secret"));const row=sqlite.prepare("SELECT ciphertext FROM hub_secrets").get();assert.ok(!row.ciphertext.includes("test-windsor-secret"));assert.equal((await (await connections.GET()).json()).connections.length,2)});
test("connections anonymous denied",async()=>{globalThis.__hubTest.user=null;assert.equal((await connections.GET()).status,403)});
test("connections cross origin denied",async()=>{assert.equal((await req(connections.POST,{apiKey:"test-windsor-secret"},"https://evil.example")).status,403)});
test("disconnect removes encrypted key",async()=>{await setup();await req(connections.POST,{action:"disconnect"});assert.equal((await (await connections.GET()).json()).configured,false)});
test("malformed provider data cannot fake connected",async()=>{globalThis.fetch=async()=>Response.json({bad:true});const r=await req(connections.POST,{apiKey:"test-windsor-secret"});assert.equal(r.status,200);const d=await r.json();assert.equal(d.configured,true);assert.ok(d.error);assert.equal(d.checkedAt,null)});
test("pending social send rejected",async()=>{await seed();assert.equal((await req(social.POST,{id,revision:0,channel:"facebook_organic"})).status,409);assert.equal(sends,0)});
test("approved social send saves provider receipt",async()=>{await setup();const r=await req(social.POST,{id,revision:1,channel:"facebook_organic"});assert.equal(r.status,200);assert.equal(sends,1);assert.equal(sqlite.prepare("SELECT status FROM social_publications").get().status,"published")});
test("duplicate send blocked",async()=>{await setup();await req(social.POST,{id,revision:1,channel:"facebook_organic"});assert.equal((await req(social.POST,{id,revision:1,channel:"facebook_organic"})).status,409);assert.equal(sends,1)});
test("uncertain provider response blocked from retry",async()=>{await setup();failSend=true;assert.equal((await req(social.POST,{id,revision:1,channel:"facebook_organic"})).status,503);assert.equal(sqlite.prepare("SELECT status FROM social_publications").get().status,"needs_review");assert.equal((await req(social.POST,{id,revision:1,channel:"facebook_organic"})).status,409);assert.equal(sends,1)});
test("stale revision rejected",async()=>{await setup();assert.equal((await req(social.POST,{id,revision:0,channel:"facebook_organic"})).status,409)});
test("cross origin social rejected",async()=>{await setup();assert.equal((await req(social.POST,{id,revision:1,channel:"facebook_organic"},"https://evil.example")).status,403)});
test("history owner protected",async()=>{globalThis.__hubTest.user=null;assert.equal((await social.GET()).status,403)});
test("Instagram length gate sends nothing",async()=>{await setup();sqlite.prepare("UPDATE articles SET body=? WHERE id=?").run("a".repeat(2300),id);assert.equal((await req(social.POST,{id,revision:1,channel:"instagram"})).status,400);assert.equal(sends,0)});
test("unavailable actions block publication",async()=>{await setup();const old=globalThis.fetch;globalThis.fetch=async(u,o)=>String(u).includes("mcp.windsor.ai")&&JSON.parse(o.body).method==="tools/call"?Response.json({jsonrpc:"2.0",id:2,result:{content:[{type:"text",text:JSON.stringify([{id:"facebook_organic",accounts:[{id:"1053341001203753"}],actions:[]}])}]}}):old(u,o);assert.equal((await req(social.POST,{id,revision:1,channel:"facebook_organic"})).status,409);assert.equal(sends,0)});

test("transport failure preserves encrypted key and reports unverified",async()=>{globalThis.fetch=async()=>{throw Error("network unavailable")};const r=await req(connections.POST,{apiKey:"test-windsor-secret"});const d=await r.json();assert.equal(d.configured,true);assert.ok(d.error);assert.equal(d.checkedAt,null);assert.ok(sqlite.prepare("SELECT ciphertext FROM hub_secrets").get());const check=await (await connections.GET()).json();assert.equal(check.configured,true);assert.ok(check.error)});

test("redirect response never forwards the key",async()=>{let calls=0;globalThis.fetch=async(u,o)=>{calls++;assert.equal(o.redirect,"manual");return new Response(null,{status:302,headers:{Location:"https://untrusted.example/"}})};const r=await req(connections.POST,{apiKey:"test-windsor-secret"});const d=await r.json();assert.equal(calls,1);assert.equal(d.configured,true);assert.match(d.error,/request failed/);assert.equal(d.checkedAt,null)});

test("MCP event stream and session headers discover VINCONNECT accounts",async()=>{const old=globalThis.fetch;globalThis.fetch=async(u,o)=>{if(String(u).includes("mcp.windsor.ai")){const input=JSON.parse(o.body);if(input.method==="initialize")return Response.json({jsonrpc:"2.0",id:1,result:{protocolVersion:"2025-03-26"}},{headers:{"Mcp-Session-Id":"test-session"}});assert.equal(o.headers["Mcp-Session-Id"],"test-session");const r=await old(u,o);if(input.method==="tools/call")return new Response("event: message\ndata: "+JSON.stringify(await r.json())+"\n\n",{headers:{"Content-Type":"text/event-stream"}});return r;}return old(u,o);};const r=await setup();const d=await r.json();assert.equal(d.connections[0].connected,true);assert.equal(d.connections[1].actionAvailable,true)});

test("explicit repost creates a separate receipt",async()=>{await setup();await req(social.POST,{id,revision:1,channel:'facebook_organic'});const r=await req(social.POST,{id,revision:1,channel:'facebook_organic',repost:true,attemptId:'abcdefghijklmnop'});assert.equal(r.status,200);assert.equal(sends,2);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM social_publications').get().n,2)});
test("same repost identifier cannot send twice",async()=>{await setup();const input={id,revision:1,channel:'facebook_organic',repost:true,attemptId:'abcdefghijklmnop'};await req(social.POST,input);assert.equal((await req(social.POST,input)).status,409);assert.equal(sends,1)});
test("both social destinations keep separate receipts",async()=>{await setup();await req(social.POST,{id,revision:1,channel:'facebook_organic'});await req(social.POST,{id,revision:1,channel:'instagram'});assert.equal(sends,2);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM social_publications').get().n,2)});
test("receipt includes post URL and exact approved snapshot",async()=>{await setup();await req(social.POST,{id,revision:1,channel:'facebook_organic'});const r=sqlite.prepare('SELECT * FROM social_publications').get();assert.equal(r.post_url,'https://www.facebook.com/123');assert.equal(r.provider_id,'123');assert.equal(r.revision,1);assert.ok(r.caption.length>20)});
test("provider errors are visible and key is redacted",async()=>{await setup();const old=globalThis.fetch;globalThis.fetch=async(u,o)=>{const input=JSON.parse(o.body);if(input.params?.name==='execute_action')return Response.json({jsonrpc:'2.0',id:2,result:{isError:true,content:[{type:'text',text:'Permission pages_manage_posts missing test-windsor-secret'}]}});return old(u,o);};const r=await req(social.POST,{id,revision:1,channel:'facebook_organic'});const d=await r.json();assert.match(d.error,/pages_manage_posts/);assert.ok(!d.error.includes('test-windsor-secret'))});
test("resolve unknown as not published permits a fresh retry",async()=>{await setup();failSend=true;await req(social.POST,{id,revision:1,channel:'facebook_organic'});const row=sqlite.prepare('SELECT id FROM social_publications').get();assert.equal((await req(social.PATCH,{id:row.id,action:'resolve',outcome:'not_published',confirmed:true})).status,200);failSend=false;assert.equal((await req(social.POST,{id,revision:1,channel:'facebook_organic',attemptId:'new-request-123456'})).status,200)});
test("resolution requires explicit confirmation",async()=>{await setup();failSend=true;await req(social.POST,{id,revision:1,channel:'facebook_organic'});const row=sqlite.prepare('SELECT id FROM social_publications').get();assert.equal((await req(social.PATCH,{id:row.id,action:'resolve',outcome:'not_published'})).status,400)});
test("post URL rejects foreign sites",async()=>{await setup();await req(social.POST,{id,revision:1,channel:'facebook_organic'});const row=sqlite.prepare('SELECT id FROM social_publications').get();assert.equal((await req(social.PATCH,{id:row.id,action:'link',postUrl:'https://evil.example/'})).status,400)});
test("history link updates are owner protected",async()=>{globalThis.__hubTest.user=null;assert.equal((await req(social.PATCH,{id:'x',action:'link'})).status,403)});
test("duplicate creates a pending draft with image",async()=>{await setup();const r=await req(manage.POST,{id,revision:1,action:'duplicate'});assert.equal(r.status,200);const d=await r.json();assert.equal(d.article.status,'pending');assert.equal(d.article.revision,0);assert.notEqual(d.article.id,id);assert.equal(d.article.image,'/assets/articles/article-1.png')});
test("unpublish removes public URL and approval",async()=>{await setup();await send({id,revision:1,action:'publish',channel:'hub'});assert.equal((await req(manage.POST,{id,revision:2,action:'unpublish'})).status,200);const a=sqlite.prepare('SELECT * FROM articles WHERE id=?').get(id);assert.equal(a.status,'pending');assert.equal(a.published_url,null);assert.equal(a.approved_by,null)});
test("stale unpublish cannot overwrite newer record",async()=>{await setup();assert.equal((await req(manage.POST,{id,revision:0,action:'unpublish'})).status,409)});
test("social failure does not prevent Hub publication",async()=>{await setup();failSend=true;await req(social.POST,{id,revision:1,channel:'facebook_organic'});assert.equal((await send({id,revision:1,action:'publish',channel:'hub'})).status,200)});

test("mark removed only updates a previously published record",async()=>{await setup();await req(social.POST,{id,revision:1,channel:'facebook_organic'});const row=sqlite.prepare('SELECT id FROM social_publications').get();assert.equal((await req(social.PATCH,{id:row.id,action:'removed',confirmed:true})).status,200);assert.equal(sqlite.prepare('SELECT status FROM social_publications').get().status,'removed');assert.equal(sends,1)});

const denial='Facebook write action failed for page 1053341001203753: (#200) The permission(s) pages_manage_posts are not available. It could be because either they are deprecated or need to be approved by App Review.';
function denyFacebook(shape='mcp'){const old=globalThis.fetch;globalThis.fetch=async(u,o)=>{const input=JSON.parse(o.body);if(input.params?.name==='execute_action'&&input.params.arguments.connector==='facebook_organic'){sends++;return Response.json({jsonrpc:'2.0',id:2,result:shape==='mcp'?{isError:true,content:[{type:'text',text:denial}]}:{content:[{type:'text',text:JSON.stringify({error:denial})}]}});}return old(u,o);};}
for(const shape of ['mcp','payload'])test('explicit permission rejection is failed with no manual-reset loop '+shape,async()=>{await setup();denyFacebook(shape);const first=await req(social.POST,{id,revision:1,channel:'facebook_organic',attemptId:'attempt-one-123456'});assert.equal(first.status,422);assert.equal((await first.json()).code,'FACEBOOK_PERMISSION_DENIED');assert.equal(sqlite.prepare('SELECT status FROM social_publications').get().status,'failed');assert.equal((await req(social.POST,{id,revision:1,channel:'facebook_organic',attemptId:'attempt-two-123456'})).status,422);assert.equal(sends,2);assert.equal((await req(social.POST,{id,revision:1,channel:'instagram'})).status,200);});
test('connection refresh retains known publishing denial',async()=>{await setup();denyFacebook();await req(social.POST,{id,revision:1,channel:'facebook_organic'});const d=await (await connections.GET()).json();assert.equal(d.connections[0].connected,true);assert.match(d.connections[0].publishingIssue,/pages_manage_posts/);assert.equal(d.connections[1].publishingIssue,undefined);});
test('old explicit permission rejection is automatically reconciled before retry',async()=>{await setup();sqlite.prepare("INSERT INTO social_publications(id,article_id,channel,status,receipt,updated_at) VALUES (?,?,?,'needs_review',?,?)").run('legacy',id,'facebook_organic',denial,new Date().toISOString());const r=await req(social.POST,{id,revision:1,channel:'facebook_organic',attemptId:'fresh-retry-123456'});assert.equal(r.status,200);assert.equal(sqlite.prepare("SELECT status FROM social_publications WHERE id='legacy'").get().status,'failed');});
test('unknown blocker returns exact attempt for inline recovery',async()=>{await setup();failSend=true;await req(social.POST,{id,revision:1,channel:'facebook_organic'});const r=await req(social.POST,{id,revision:1,channel:'facebook_organic',attemptId:'fresh-retry-123456'});const d=await r.json();assert.equal(d.code,'OUTCOME_UNKNOWN');assert.equal(d.attempt.id,id+':facebook_organic');});
test('published race during schema lookup cannot bypass repost consent',async()=>{await setup();const old=globalThis.fetch;globalThis.fetch=async(u,o)=>{const input=JSON.parse(o.body);if(input.params?.name==='list_actions')sqlite.prepare("INSERT INTO social_publications(id,article_id,channel,status,updated_at) VALUES ('race',?,?,'published',?)").run(id,'facebook_organic',new Date().toISOString());return old(u,o);};assert.equal((await req(social.POST,{id,revision:1,channel:'facebook_organic',attemptId:'fresh-retry-123456'})).status,409);assert.equal(sends,0);});
test('late completion never overwrites a resolved record',async()=>{await setup();const old=globalThis.fetch;globalThis.fetch=async(u,o)=>{if(JSON.parse(o.body).params?.name==='execute_action')sqlite.prepare("UPDATE social_publications SET status='failed'").run();return old(u,o);};assert.equal((await req(social.POST,{id,revision:1,channel:'facebook_organic'})).status,409);assert.equal(sqlite.prepare('SELECT status FROM social_publications').get().status,'failed');});

const job={suburb:'Nyora',service:'Starlink installation',mount:'Wall bracket',challenge:'Trees near the roof',result:'Dish mounted above the roof line',headline:'Connected in Nyora',style:'local'};
function jpeg(w=1080,h=1350){return new Uint8Array([255,216,255,192,0,17,8,h>>8,h&255,w>>8,w&255,3,1,17,0,2,17,0,3,17,0,255,217]);}
async function uploadTest(kind='render',bytes=jpeg()){return uploads.POST(new Request('https://hub.example/api/uploads?kind='+kind,{method:'POST',headers:{Origin:'https://hub.example','Content-Type':'image/jpeg'},body:bytes}));}
async function installationDraft(count=1){const photos=[];for(let i=0;i<count;i++){const source=(await (await uploadTest('source')).json()).path;const rendered=(await (await uploadTest()).json()).path;photos.push({source,rendered,brightness:100,contrast:100});}return {id:'vinconnect-install-'+crypto.randomUUID(),revision:null,title:'Starlink installation in Nyora',body:'A clean installation with careful planning. Message VINCONNECT for your next job.',job,photos};}
async function readMedia(path){return media.GET(new Request('https://hub.example'+path),{params:Promise.resolve({id:path.split('/').pop()})});}
test('upload requires owner identity',async()=>{globalThis.__hubTest.user=null;assert.equal((await uploadTest()).status,403)});
test('export dimensions are enforced',async()=>{assert.equal((await uploadTest('render',jpeg(600,400))).status,400)});
test('non-JPEG bytes rejected',async()=>{assert.equal((await uploadTest('render',new Uint8Array([1,2,3]))).status,400)});
test('installation saves ordered media and job details durably',async()=>{const d=await installationDraft(2);const r=await req(installations.POST,d);assert.equal(r.status,200);const saved=(await r.json()).article;assert.equal(saved.status,'pending');assert.deepEqual(JSON.parse(saved.media_json),d.photos);assert.deepEqual(JSON.parse(saved.job_json),job);assert.equal((await (await GET()).json()).articles.find(a=>a.id===d.id).title,d.title)});
test('only approved exports become public; sources stay private',async()=>{const d=await installationDraft();await req(installations.POST,d);const owner=globalThis.__hubTest.user;globalThis.__hubTest.user=null;assert.equal((await readMedia(d.photos[0].rendered)).status,404);globalThis.__hubTest.user=owner;assert.equal((await send({id:d.id,revision:0,action:'approve'})).status,200);globalThis.__hubTest.user=null;assert.equal((await readMedia(d.photos[0].rendered)).status,200);assert.equal((await readMedia(d.photos[0].source)).status,404)});
test('stale installation edits never overwrite',async()=>{const d=await installationDraft();await req(installations.POST,d);assert.equal((await req(installations.POST,{...d,revision:7,title:'Wrong revision'})).status,409);assert.equal(sqlite.prepare('SELECT title FROM articles WHERE id=?').get(d.id).title,d.title)});
test('edited approved installation returns to pending',async()=>{const d=await installationDraft();await req(installations.POST,d);await send({id:d.id,revision:0,action:'approve'});const r=await req(installations.POST,{...d,revision:1,title:'Updated installation'});assert.equal(r.status,200);assert.equal((await r.json()).article.status,'pending')});
test('unknown media cannot be saved',async()=>{const d=await installationDraft();d.photos[0].rendered='/media/'+crypto.randomUUID()+'.jpg';assert.equal((await req(installations.POST,d)).status,400)});
test('source photo cannot masquerade as approved render',async()=>{const d=await installationDraft();d.photos[0].rendered=d.photos[0].source;assert.equal((await req(installations.POST,d)).status,400)});
test('installation creation retries do not duplicate',async()=>{const d=await installationDraft();await req(installations.POST,d);assert.equal((await req(installations.POST,d)).status,409);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM articles WHERE id=?').get(d.id).n,1)});
test('Instagram carousel sends ordered public URLs',async()=>{await setup();const d=await installationDraft(2);await req(installations.POST,d);await send({id:d.id,revision:0,action:'approve'});const old=globalThis.fetch;let sent;globalThis.fetch=async(u,o)=>{const input=JSON.parse(o.body);if(input.params?.name==='list_actions')return Response.json({jsonrpc:'2.0',id:2,result:{content:[{type:'text',text:JSON.stringify([{id:'create_carousel_post',schema:{properties:{image_urls:{type:'array'},caption:{type:'string'}}}}])}]}});if(input.params?.name==='execute_action'){sent=input.params.arguments;return Response.json({jsonrpc:'2.0',id:2,result:{content:[{type:'text',text:JSON.stringify({id:'123',permalink:'https://www.instagram.com/p/example/'})}]}});}return old(u,o);};const r=await req(social.POST,{id:d.id,revision:1,channel:'instagram'});assert.equal(r.status,200);assert.equal(sent.action,'create_carousel_post');assert.deepEqual(sent.params.image_urls,d.photos.map(p=>'https://vinconnect-media.fgymjki.chatgpt.site'+p.rendered));});
test('unavailable carousel action sends nothing',async()=>{await setup();const d=await installationDraft(2);await req(installations.POST,d);await send({id:d.id,revision:0,action:'approve'});assert.equal((await req(social.POST,{id:d.id,revision:1,channel:'instagram'})).status,409);assert.equal(sends,0)});
test('installation cross-origin save denied',async()=>{assert.equal((await req(installations.POST,{},'https://evil.example')).status,403)});
