'use client';
import {TemplateGallery} from './template-gallery';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {brandCanvas,sourcePhoto,canvasBlob} from '../lib/brand-renderer';
import {buildJobCaption,emptyJob,type JobDetails,type JobPhoto} from '../lib/install-content';
import {designLayouts,builtInTemplates,defaultTemplate,postTypes,type BrandTemplate} from '../lib/brand-templates';
type Existing={id:string;revision:number;title:string;body:string;image:string;media_json?:string|null;job_json?:string|null};
export function InstallEditor({article,onSaved,onClose,initialTemplate}:{initialTemplate?:BrandTemplate;article:Existing|null;onSaved:()=>void;onClose:()=>void}){
 const [id]=useState(()=>article?.id||'vinconnect-install-'+crypto.randomUUID());
 const [job,setJob]=useState<JobDetails>(()=>article?.job_json?JSON.parse(article.job_json):{...emptyJob,brand:initialTemplate,headline:article?.title?.slice(0,100)||emptyJob.headline});
 const [photos,setPhotos]=useState<JobPhoto[]>(()=>article?.media_json?JSON.parse(article.media_json):article?[{source:article.image,rendered:'',brightness:100,contrast:100}]:[]);
 const [title,setTitle]=useState(article?.title||''),[body,setBody]=useState(article?.body||''),[active,setActive]=useState(0),[preview,setPreview]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[dirty,setDirty]=useState(false);
 const [templates,setTemplates]=useState<{id:string;name:string;settings:BrandTemplate}[]>([]),[templateName,setTemplateName]=useState(''),[templateMessage,setTemplateMessage]=useState('');
 const template=job.brand||defaultTemplate;
 const install=(template.type||'Installations')==='Installations';
 async function loadTemplates(){try{const r=await fetch('/api/brand-templates');const d:any=await r.json();if(!r.ok)throw Error(d.error);setTemplates(d.templates);setTemplateMessage('');}catch(e){setTemplateMessage((e as Error).message);}}
 useEffect(()=>{void loadTemplates();},[]);
 function setBrand(value:BrandTemplate){setProgress('Brand template applied. Review the graphic before saving.');setJob(j=>({...j,brand:value}));setDirty(true);}
 async function saveTemplate(){if(running.current)return;running.current=true;setBusy(true);try{const r=await fetch('/api/brand-templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:templateName,settings:template})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setTemplates(t=>[d.template,...t]);setTemplateMessage('Template saved. It is available for future posts.');setTemplateName('');}catch(e){setTemplateMessage((e as Error).message);}finally{running.current=false;setBusy(false);}}
 const running=useRef(false),photo=photos[active];
 useEffect(()=>{let cancelled=false;let url='';setPreview('');if(photo)brandCanvas(photo.source,job,photo.brightness,photo.contrast,active,photos.length,photos).then(canvas=>canvasBlob(canvas)).then(blob=>{url=URL.createObjectURL(blob);if(!cancelled)setPreview(url);else URL.revokeObjectURL(url);}).catch(e=>!cancelled&&setError(e.message));return()=>{cancelled=true;if(url)URL.revokeObjectURL(url);};},[photo,job,active,photos]);
 useEffect(()=>{const prevent=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty,busy]);
 function close(){if(!busy&&(!dirty||confirm('Discard unsaved post edits?')))onClose();}
 async function upload(blob:Blob,kind:string){const response=await fetch('/api/uploads?kind='+kind,{method:'POST',headers:{'Content-Type':'image/jpeg'},body:blob});const data:any=await response.json();if(!response.ok)throw Error(data.error);return data.path as string;}
 async function add(files:FileList|null){if(!files||running.current)return;if(photos.length+files.length>10){setError('Choose up to 10 photos for one post.');return;}running.current=true;setBusy(true);setError('');try{for(const [i,file] of Array.from(files).entries()){setProgress(`Preparing photo ${i+1} of ${files.length}…`);const blob=await sourcePhoto(file);const source=await upload(blob,'source');setPhotos(old=>[...old,{source,rendered:'',brightness:100,contrast:100}]);setDirty(true);}}catch(e){setError((e as Error).message);}finally{setBusy(false);running.current=false;setProgress('');}}
 function updateJob(key:Exclude<keyof JobDetails,'brand'>,value:string){setJob(j=>({...j,[key]:value}));setDirty(true);}
 function adjust(key:'brightness'|'contrast',value:number){setPhotos(all=>all.map((p,i)=>i===active?{...p,[key]:value}:p));setDirty(true);}
 function move(index:number,to:number){if(to<0||to>=photos.length)return;setPhotos(all=>{const next=[...all];[next[index],next[to]]=[next[to],next[index]];return next;});setActive(to);setDirty(true);}
 async function save(){if(running.current)return;if(!photos.length||title.trim().length<3||body.trim().length<20){setError('Add a photo, a title and at least 20 characters of caption.');return;}running.current=true;setBusy(true);setError('');try{const rendered:JobPhoto[]=[];for(let i=0;i<photos.length;i++){setProgress(`Saving branded photo ${i+1} of ${photos.length}…`);const p=photos[i];const canvas=await brandCanvas(p.source,job,p.brightness,p.contrast,i,photos.length,photos);rendered.push({...p,rendered:await upload(await canvasBlob(canvas),'render')});}
 const response=await fetch('/api/installations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,revision:article?.revision??null,title,body,job,photos:rendered})});const data:any=await response.json();if(!response.ok)throw Error(data.error);setDirty(false);onSaved();
 }catch(e){setError((e as Error).message);}finally{running.current=false;setBusy(false);setProgress('');}}
 async function copyBrief(){try{await navigator.clipboard.writeText('Write a polished VINCONNECT social caption using only these post details. Use Australian English, short paragraphs, a clear call to action and up to 5 relevant hashtags. Do not invent speeds, client names, results or equipment. Keep title plus caption under 2,200 characters. Return plain text, no Markdown.\n'+JSON.stringify(job,null,2));setProgress('AI brief copied. Paste it into ChatGPT, then paste the caption below.');}catch{setError('Clipboard unavailable. You can copy the job details manually.');}}
 return <Dialog open onOpenChange={open=>!open&&close()}><DialogContent className="install-modal"><DialogTitle>{article?'Polish post & graphics':'New post'}</DialogTitle><DialogDescription>Choose a post type and add your content. Preview every photo, save a draft, then approve and publish.</DialogDescription>
 <div className="install-columns"><section className="install-fields"><fieldset disabled={busy}><legend>1. Post details</legend><label>Post type<input list="post-type-options" maxLength={60} value={template.type||'Installations'} onChange={e=>setBrand({...template,type:e.target.value})}/><datalist id="post-type-options">{postTypes.map(t=><option key={t} value={t}/>)}</datalist></label><div className="job-pair"><label>Suburb<input maxLength={100} placeholder="e.g. Nyora" value={job.suburb} onChange={e=>updateJob('suburb',e.target.value)}/></label><label>{install?'Service':'Topic'}<input maxLength={100} value={job.service} onChange={e=>updateJob('service',e.target.value)}/></label></div><label>{install?'Mount / equipment':'Key point (optional)'}<input maxLength={100} placeholder="Describe the actual installation" value={job.mount} onChange={e=>updateJob('mount',e.target.value)}/></label><label>{install?'What needed solving?':'What should readers know?'}<textarea maxLength={800} value={job.challenge} onChange={e=>updateJob('challenge',e.target.value)}/></label><label>{install?'What did you deliver?':'Supporting details / offer terms'}<textarea maxLength={800} value={job.result} onChange={e=>updateJob('result',e.target.value)}/></label>
 <legend>2. Photos & branding</legend><label className="upload-zone">Add photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{add(e.target.files);e.target.value='';}}/></label><p className="caption">Up to 10 photos. JPEG, PNG or WebP. Source photos stay private. Approved branded exports become accessible by link for publishing.</p>
 <div className="photo-strip">{photos.map((p,i)=><div key={p.source+i} className={active===i?'photo-tile selected':'photo-tile'}><button aria-label={`Edit photo ${i+1}`} onClick={()=>setActive(i)}><img src={p.source} alt={`Job photo ${i+1}`}/><span>{i===0?'Cover':`Photo ${i+1}`}</span></button><div><button aria-label={`Move photo ${i+1} earlier`} disabled={i===0} onClick={()=>move(i,i-1)}>←</button><button aria-label={`Move photo ${i+1} later`} disabled={i===photos.length-1} onClick={()=>move(i,i+1)}>→</button><button aria-label={`Remove photo ${i+1}`} onClick={()=>{setPhotos(all=>all.filter((_,n)=>n!==i));setActive(0);setDirty(true);}}>×</button></div></div>)}</div>
 <details><summary>Browse Brand Templates</summary><TemplateGallery onSelect={setBrand}/></details>
 <div className="brand-template-controls"><label>Reusable VINCONNECT template<select value="" onChange={e=>{const chosen=[...builtInTemplates,...templates].find(t=>t.id===e.target.value);if(chosen)setBrand({...chosen.settings});}}><option value="" disabled>Choose a preset or saved template</option><optgroup label="VINCONNECT presets">{builtInTemplates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</optgroup><optgroup label="Your saved templates">{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</optgroup></select></label><div className="job-pair"><label>Design layout<select value={template.layout} onChange={e=>setBrand({...template,layout:e.target.value as BrandTemplate['layout']})}>{designLayouts.map(([id,name])=><option key={id} value={id}>{name}</option>)}<option value="spotlight">Photo spotlight</option><option value="editorial">Editorial split</option><option value="campaign">Bold campaign</option><option value="classic">Charcoal</option><option value="white">Clean white</option><option value="teal">Teal</option></select></label><label>Image format<select value={template.format} onChange={e=>setBrand({...template,format:e.target.value as BrandTemplate['format']})}><option value="portrait">Portrait · 4:5</option><option value="square">Square · 1:1</option><option value="landscape">Landscape · 3:2</option></select></label></div><label>Photo framing<select value={template.photoFit||'fill'} onChange={e=>setBrand({...template,photoFit:e.target.value as 'fill'|'contain'})}><option value="fill">Fill frame · crops edges</option><option value="contain">Show full photo · no crop</option></select></label><label>Top label<input maxLength={40} value={template.label} onChange={e=>setBrand({...template,label:e.target.value})}/></label><label>Headline pattern<input maxLength={140} value={template.headline} onChange={e=>setBrand({...template,headline:e.target.value})}/></label><label>Location / service pattern<input maxLength={140} value={template.subline} onChange={e=>setBrand({...template,subline:e.target.value})}/></label><p className="caption">Use {'{headline}'}, {'{suburb}'} and {'{service}'} to fill banners from the job fields. Your logo, colours and contact details stay consistent.</p><label>Save this template for future posts<input maxLength={60} placeholder="e.g. Local installs — square" value={templateName} onChange={e=>setTemplateName(e.target.value)}/></label><button disabled={!templateName.trim()} onClick={saveTemplate}>Save reusable template</button>{templateMessage&&<p role="status">{templateMessage}</p>}<button onClick={loadTemplates}>Refresh saved templates</button></div>
 <details className="ai-photo-status"><summary>AI photo cleanup & inspiration</summary><p>AI image editing is not connected yet. Brightness, contrast and branded templates work now.</p><p>Cleanup will need to preserve your actual dish, mount and installation. Inspiration images will need a separate review before use.</p></details>
 <label>Feature lines on graphic (up to three)<textarea maxLength={240} value={job.graphicFeatures||''} onChange={e=>updateJob('graphicFeatures',e.target.value)} placeholder={'Starlink installation\nShed Wi-Fi link\nInternal cable run'}/></label><label>Circular callout (optional)<input maxLength={60} value={job.graphicBadge||''} onChange={e=>updateJob('graphicBadge',e.target.value)} placeholder="e.g. Wi-Fi to the shed"/></label><p className="caption">Use verified details only. Collage designs use up to two other photos from this post.</p><label>Graphic headline<input maxLength={100} value={job.headline} onChange={e=>updateJob('headline',e.target.value)}/></label>{photo&&<div className="job-pair"><label>Brightness · {photo.brightness}%<input type="range" min={80} max={120} value={photo.brightness} onChange={e=>adjust('brightness',Number(e.target.value))}/></label><label>Contrast · {photo.contrast}%<input type="range" min={80} max={120} value={photo.contrast} onChange={e=>adjust('contrast',Number(e.target.value))}/></label></div>}
 <legend>3. Caption</legend><label>Tone<select value={job.style} onChange={e=>updateJob('style',e.target.value)}><option value="local">Friendly & local</option><option value="brief">Short & direct</option></select></label><div className="editor-tools"><button onClick={()=>{if(body&&!confirm('Replace the current title and caption with a draft from these fields?'))return;const draft=buildJobCaption(job);setTitle(draft.title);setBody(draft.body);setDirty(true);}}>Build caption from fields</button><button onClick={copyBrief}>Copy brief for ChatGPT</button></div><p className="caption">The built-in caption builder uses your fields. For AI wording, copy the brief into ChatGPT and paste its draft below.</p>
 <label>Post title<input maxLength={180} value={title} onChange={e=>{setTitle(e.target.value);setDirty(true);}}/></label><div className="editor-tools"><button onClick={()=>{setBody(text=>text+'\n\n');setDirty(true);}}>Add paragraph break</button><button onClick={()=>{setBody(text=>text+'\n• ');setDirty(true);}}>Add bullet</button></div><label>Caption<textarea className="caption-input" maxLength={20000} value={body} onChange={e=>{setBody(e.target.value);setDirty(true);}}/></label><p className={title.length+body.length+2>2200?'alert':'caption'}>{title.length+body.length+2} / 2,200 characters for Instagram. Use paragraphs and bullets; Markdown bold is not supported.</p></fieldset></section>
 <section className="install-preview"><span className="eyebrow">YOUR BRANDED POST</span>{preview?<img className="branded-preview" src={preview} alt="Branded post preview"/>:<div className="preview-empty">{photo?'Preparing preview…':'Add your first installation photo'}</div>}<div className="social-caption"><strong>{title||'Your post title'}</strong><p>{body||'Your caption will appear here.'}</p></div>{preview&&<a href={preview} download="vinconnect-post.jpg">Download this branded image</a>}<p className="caption">Original logo, teal banner and contact details are baked into every export. Fill frame crops edges; choose Show full photo to retain the whole image. Overlays may cover parts of the image. Review equipment visibility before approval.</p></section></div>
 {error&&<p role="alert" className="alert">{error}</p>}{progress&&<p role="status">{progress}</p>}<div className="install-footer"><button disabled={busy} onClick={close}>Cancel</button><button className="primary" disabled={busy||!photos.length} onClick={save}>{busy?'Working…':'Save as pending for approval'}</button></div>
 </DialogContent></Dialog>;
}
