"use client";
import {TemplateGallery} from "./template-gallery";
import type {BrandTemplate} from "../lib/brand-templates";
import {InstallEditor} from "./install-editor";
import {useEffect,useState} from "react";
import {WindsorPanel,SocialPublish,SocialHistory} from "./windsor-panel";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
type Article={id:string;title:string;body:string;category:string;image:string;status:string;revision:number;published_url:string|null;published_at:string|null;media_json?:string|null;job_json?:string|null};
const connections=[
{name:"Facebook",key:"facebook_organic",detail:"Vinconnect Starlink Solutions (1053341001203753) is connected in Windsor after reauthorisation. Photo and text actions are listed. Meta publishing permission remains unverified. Use the Windsor live connection form in Connections to authorise this Hub.",url:"https://onboard.windsor.ai/connect?connector=facebook_organic&client=CHATGPT&next=/facebook_organic/authorize"},
{name:"Instagram",key:"instagram",detail:"Use the Windsor live connection form in Connections to authorise this Hub. Live status is checked against Windsor.",url:"https://onboard.windsor.ai/connect?connector=instagram&client=CHATGPT&next=/instagram/authorize"},
{name:"X",key:"twitter",detail:"Open Windsor account setup. The exposed X connector has no publishing action, so direct Hub posting is unavailable.",url:"https://onboard.windsor.ai/connect?connector=twitter&client=CHATGPT&next=/twitter/authorize"},
{name:"Website",key:"website",detail:"Approved and published Hub posts are available in Website admin → Media Hub. Choose a post there, review its suburb and image, then publish it to the VINCONNECT website.",url:"https://vinconnect-website-base.fgymjki.chatgpt.site/admin"},
{name:"Google Drive",key:"drive",detail:"Your ChatGPT Drive connection does not automatically authorise this website. Direct file import needs a Google OAuth application and server integration. You can open Drive below to review your source images.",url:"https://drive.google.com/drive/u/0/home"},
{name:"Dropbox",key:"dropbox",detail:"Reference images have been retrieved through your connected ChatGPT Dropbox account. Direct import inside the Hub needs its own Dropbox OAuth application and server integration.",url:"https://www.dropbox.com/home"},
{name:"OpenAI",key:"openai",detail:"These 15 articles were drafted in ChatGPT. Live generation inside the Hub requires an OpenAI API connection. No live AI generation is currently enabled.",url:"https://platform.openai.com/api-keys"}
];
export function MediaHub({user,signOutPath}:{user:{name:string;email:string};signOutPath:string}){
const [editingInstall,setEditingInstall]=useState<{article:Article|null;template?:BrandTemplate}|null>(null);
const [historyVersion,setHistoryVersion]=useState(0);
const [articles,setArticles]=useState<Article[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
const [filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Article|null>(null),[config,setConfig]=useState<typeof connections[number]|null>(null),[publishing,setPublishing]=useState<Article|null>(null),[view,setView]=useState("dashboard");
async function refresh(){setHistoryVersion(v=>v+1);setLoading(true);setError("");try{const r=await fetch("/api/articles",{cache:"no-store"});const d=await r.json() as {error?:string;articles:Article[]};if(!r.ok)throw Error(d.error);setArticles(d.articles);setPublishing(prev=>prev?d.articles.find(a=>a.id===prev.id)||null:null);}catch(e){setError((e as Error).message||"Could not load articles.");}finally{setLoading(false);}}
useEffect(()=>{refresh()},[]);
async function manage(a:Article,act:string){
 if(act==='unpublish'&&!confirm('Remove this public Hub article and return it to pending? Social posts will remain live.'))return;
 setBusy(true);setError('');try{const r=await fetch('/api/articles/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:a.id,revision:a.revision,action:act})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setSelected(d.article||null);await refresh();setNotice(act==='duplicate'?'New pending copy created. Edit and approve it before publishing.':'Removed from the Hub website. You can edit and approve it again.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}
}
async function action(a:Article,act:string){
setBusy(true);setError("");setNotice("");
try{const r=await fetch("/api/articles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:a.id,revision:a.revision,title:a.title,body:a.body,action:act,channel:"hub"})});const d=await r.json() as {error?:string;article:Article};if(!r.ok)throw Error(d.error);setArticles(old=>old.map(x=>x.id===a.id?d.article:x));setSelected(null);setPublishing(null);setNotice(act==="publish"?"Published on the Hub website.":act==="approve"?"Approved. Ready for your publishing decision.":act==="save"?"Saved as pending. Changes need approval.":"Returned to pending.");}
catch(e){setError((e as Error).message||"Action failed.");}finally{setBusy(false);}
}
const shown=articles.filter(a=>(filter==="all"||a.status===filter)&&[a.title,a.category,a.body].join(" ").toLowerCase().includes(query.toLowerCase()));
const dirty=selected&&articles.some(a=>a.id===selected.id&&(a.title!==selected.title||a.body!==selected.body));
return <main className="hub">
<aside className="rail"><img src="/assets/vinconnect-transparent.png" alt="VINCONNECT"/><p>MEDIA HUB</p><nav>{[["dashboard","Dashboard"],["library","Media library"],["connections","Connections"],["templates","Brand Templates"],["brand","Brand guidelines"]].map(([k,n])=><button className={view===k?"active":""} key={k} onClick={()=>setView(k)}>{n}</button>)}<a className="workspace-link" href="https://vinconnect-website-base.fgymjki.chatgpt.site/admin" target="_blank" rel="noreferrer">Website admin ↗</a></nav><div className="account"><strong>Private workspace</strong><span>{user.email}</span><a href={signOutPath} target="_top">Sign out</a></div></aside>
<section className="workspace"><header><div><span className="eyebrow">VINCONNECT / MEDIA CENTRE</span><h1>{view==="dashboard"?"Your publishing desk":view==="library"?"Media library":view==="brand"?"Brand guidelines":view==="templates"?"Brand Templates":"Your connections"}</h1><p>Review the details. Approve the story. Choose when it goes live.</p></div><div className="editor-tools"><button className="primary" onClick={()=>setEditingInstall({article:null})}>＋ Create post</button><button onClick={refresh} disabled={loading}>Refresh status</button></div></header>
{error&&<div role="alert" className="alert">{error}<button onClick={refresh}>Reload saved state</button></div>}
{notice&&<p role="status" className="notice">{notice}</p>}
{(view==="dashboard"||view==="library")&&<>
<div className="stats">{[["all","Total drafts"],["pending","Pending review"],["approved","Approved"],["published","Published on Hub"]].map(([k,n])=><button key={k} className={filter===k?"chosen":""} onClick={()=>setFilter(k)}><span>{n}</span><strong>{loading?"—":articles.filter(a=>k==="all"||a.status===k).length}</strong></button>)}</div>
<div className="queue-head"><div><h2>{view==="library"?"Article imagery":"Review queue"}</h2><p>Review and approve a draft before choosing publishing destinations.</p></div><input aria-label="Search articles" placeholder="Search articles or topics…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
{loading?<p role="status">Loading saved articles…</p>:<div className="cards">{shown.map((a,i)=><article key={a.id} className="card"><div className="graphic"><img loading="lazy" src={a.image} alt={a.title}/>{!a.media_json&&<div className="graphic-brand"><img src="/assets/vinconnect-transparent.png" alt="VINCONNECT"/><span>{a.category}</span></div>}</div><div className="card-copy"><div className="card-meta"><span>{a.category}</span><b className={a.status}>{a.status==="pending"?"Pending review":a.status}</b></div><h3>{a.title}</h3><p>{a.body.slice(0,140)}…</p><div className="card-actions"><button onClick={()=>setSelected({...a})}>Review & edit</button>{a.status==="pending"&&<button className="primary" onClick={()=>setSelected({...a})}>Review to approve</button>}{a.status==="approved"&&<button className="primary" onClick={()=>setPublishing(a)}>Publish…</button>}{a.status==="published"&&<button onClick={()=>setPublishing(a)}>Publish to social…</button>}{a.status==="published"&&a.published_url&&<a href={a.published_url} target="_blank" rel="noreferrer">View published ↗</a>}</div></div></article>)}</div>}
{!loading&&!shown.length&&!error&&<p>No articles match this filter.</p>}
<div className="connection-note"><strong>Social publishing</strong><span>Connect Windsor once in Connections, then publish an approved article to Facebook or Instagram. Approval alone does not publish.</span><button onClick={()=>setView("connections")}>Open connections</button></div>
</>}
{view==="connections"&&<><WindsorPanel refreshKey={historyVersion}/><div className="connection-grid">{connections.filter(c=>!["facebook_organic","instagram"].includes(c.key)).map(c=><article className="connection-card" key={c.key}><span className="eyebrow">INTEGRATION</span><h2>{c.name}</h2><b>{c.key==="website"?"Hub articles supported":"Setup required"}</b><p>{c.detail}</p><button onClick={()=>setConfig(c)}>View {c.name} options</button></article>)}</div></>}
{(view==="dashboard"||view==="connections")&&<SocialHistory refreshKey={historyVersion}/>}
{view==="templates"&&<TemplateGallery onSelect={template=>setEditingInstall({article:null,template})}/>}
{view==="brand"&&<section className="brand-panel"><img src="/assets/vinconnect-transparent.png" alt="Official VINCONNECT Standard White logo"/><h2>Use the original. Keep it clear.</h2><ul><li>Standard White is the default logo. Never redraw or stretch it.</li><li>Use the supplied dish and bracket references for hardware imagery.</li><li>Use teal, white and dark charcoal. Keep text legible.</li><li>Write in a clear, local, professional voice.</li><li>No invented client results, speed guarantees or unsupported claims.</li><li>Every article and graphic needs your approval before publication.</li></ul><p>These are review guidelines, not an automated compliance certification.</p><a href="/assets/vinconnect-transparent.png" download>Download standard logo</a><h3>Corrected graphic using the supplied installation reference</h3><img className="corrected" src="/assets/vinconnect-corrected-ad.png" alt="Corrected VINCONNECT advertisement using supplied dish and bracket reference"/></section>}
</section>
<Dialog open={!!selected} onOpenChange={open=>{if(!open&&!busy){if(dirty&&!window.confirm("Discard unsaved edits?"))return;setSelected(null);}}}><DialogContent className="review-modal"><DialogTitle>Review article</DialogTitle><DialogDescription>Check the image and text. Save edits before approving. Editing an approved article returns it to pending.</DialogDescription>{selected&&<><img className="review-image" src={selected.image} alt={selected.title}/>{selected.media_json&&<div className="review-gallery">{JSON.parse(selected.media_json).slice(1).map((p:any)=><img key={p.rendered} src={p.rendered} alt="Additional carousel photo"/>)}</div>}<label>Title<input disabled={busy||selected.status==="published"} value={selected.title} onChange={e=>setSelected({...selected,title:e.target.value})}/></label><label>Article<textarea disabled={busy||selected.status==="published"} value={selected.body} onChange={e=>setSelected({...selected,body:e.target.value})}/></label><p className="caption">Review every photo and the caption. Approval makes branded exports accessible by link so publishing platforms can fetch them. Source photos remain private.</p>{error&&<p role="alert" className="alert">{error}</p>}<div className="modal-actions"><button disabled={busy||!!dirty||selected.status==="published"} onClick={()=>{setEditingInstall({article:selected});setSelected(null);}}>Polish graphics & caption</button><button disabled={busy||!dirty||selected.status==="published"} onClick={()=>action(selected,"save")}>Save changes</button>{selected.status==="pending"&&<button className="primary" disabled={busy||!!dirty} onClick={()=>action(selected,"approve")}>Approve this article & image</button>}{selected.status==="approved"&&<><button disabled={busy||!!dirty} onClick={()=>action(selected,"pending")}>Return to pending</button><button className="primary" disabled={busy||!!dirty} onClick={()=>{setPublishing(selected);setSelected(null);}}>Publish…</button></>}<button disabled={busy||!!dirty} onClick={()=>manage(selected,"duplicate")}>Duplicate as new draft</button>{selected.status==="published"&&<button disabled={busy} onClick={()=>manage(selected,"unpublish")}>Unpublish Hub article to edit</button>}<a href={selected.image} download>Download image</a><button onClick={async()=>{try{await navigator.clipboard.writeText(selected.title+"\n\n"+selected.body);setNotice("Caption copied.");}catch{setError("Clipboard unavailable. Select and copy the article text.");}}}>Copy caption</button></div></>}</DialogContent></Dialog>
<Dialog open={!!publishing} onOpenChange={o=>{if(!o&&!busy)setPublishing(null)}}><DialogContent className="review-modal compact"><DialogTitle>Publish approved article</DialogTitle><DialogDescription>Choose the destination. Publication makes this article publicly accessible.</DialogDescription><h3>{publishing?.title}</h3>{publishing&&<SocialPublish article={publishing} onBusy={setBusy} onDone={()=>{refresh();}}/>}<button onClick={()=>{setPublishing(null);setView("connections");}}>Open Windsor connection settings</button>{["Website","X"].map(n=><button key={n} onClick={()=>{setPublishing(null);setConfig(connections.find(c=>c.name===n)!);}}>Set up {n==="Website"?"vinconnect.com.au":n} publishing</button>)}{error&&<p role="alert">{error}</p>}</DialogContent></Dialog>
<Dialog open={!!config} onOpenChange={o=>!o&&setConfig(null)}><DialogContent className="review-modal compact"><DialogTitle>{config?.name} setup</DialogTitle><DialogDescription>{config?.detail}</DialogDescription><a className="primary" href={config?.url} target="_blank" rel="noopener noreferrer">Open {config?.name} {["drive","dropbox"].includes(config?.key||"")?"files":"setup"} ↗</a><p>Opening this link does not confirm connection. Live integration must be verified before the Hub can publish or import through this provider.</p></DialogContent></Dialog>
{editingInstall&&<InstallEditor initialTemplate={editingInstall.template} article={editingInstall.article} onClose={()=>setEditingInstall(null)} onSaved={()=>{setEditingInstall(null);refresh();setNotice("Branded post saved as pending. Review every photo and approve before publishing.");}}/>}
</main>;
}
