'use client';
import {useEffect,useState,useRef} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Connection={channel:string;name:string;account:string;accountName?:string;connected:boolean;actionAvailable:boolean;publishingIssue?:string;publishingIssueAt?:string};
export function WindsorPanel({refreshKey=0}:{refreshKey?:number}){
  const [state,setState]=useState<{configured:boolean;connections:Connection[];checkedAt:string|null}|null>(null);
  const inFlight=useRef(false);
  const [key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function request(body?:unknown){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{const r=await fetch('/api/connections',{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setState(d);setError(d.error||'');if(body)setKey('');}catch(e){setError((e as Error).message);}finally{inFlight.current=false;setBusy(false);}}
  useEffect(()=>{request();const timer=setInterval(()=>{if(document.visibilityState==='visible')request();},60000);const focus=()=>request();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[refreshKey]);
  return <section className="brand-panel"><h2>Windsor live connection</h2><p>Connect this Hub once using your Windsor API key. Your Facebook and Instagram authorisations stay in Windsor.</p>{error&&<p role="alert">{error} Status could not be verified.</p>}{state?.configured&&<p><strong>API key saved securely.</strong> {error?'Connection not verified.':''}</p>}{state?.checkedAt&&<p>Last checked: {new Date(state.checkedAt).toLocaleString()}</p>}{!error&&state?.connections.map(c=><p key={c.channel}><strong>{c.name}: {c.connected?'Connected':'Not connected'}</strong> · {c.accountName||c.account} · {c.actionAvailable?'Photo action available; publishing permissions are checked when you send.':'Photo publishing unavailable'}{c.publishingIssue&&<span className="alert" style={{display:'block'}}>Last publishing attempt rejected: {c.publishingIssue}</span>}</p>)}{!state?.configured&&<p>Hub authorisation required.</p>}<form onSubmit={e=>{e.preventDefault();request({apiKey:key});}}><label>Windsor API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required maxLength={1024}/></label><p>Stored encrypted. Never shown again after saving. Get your key from <a href="https://onboard.windsor.ai/app/team-management" target="_blank" rel="noreferrer">Windsor team management</a>; enable write actions there for publishing.</p><button className="primary" disabled={busy||!key.trim()}>{busy?'Checking…':state?.configured?'Save replacement & check':'Save key & check connection'}</button></form><button disabled={busy} onClick={()=>request()}>Refresh live connection</button>{state?.configured&&<button disabled={busy} onClick={()=>{if(confirm('Disconnect Windsor from this Hub? Your Windsor accounts will remain connected.'))request({action:'disconnect'});}}>Disconnect Hub</button>}</section>;
}
type PublishArticle={id:string;revision:number;title:string;body:string;image?:string;status?:string;media_json?:string|null};
export function SocialPublish({article,onDone,onBusy}:{article:PublishArticle;onDone:()=>void;onBusy?:(busy:boolean)=>void}){
 const [selected,setSelected]=useState<string[]>([]),[connections,setConnections]=useState<Connection[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[repost,setRepost]=useState(false),[results,setResults]=useState<Record<string,{message:string;url?:string;ok:boolean;code?:string;details?:string;attempt?:{id:string;status:string}}>>({});
 const running=useRef(false);
 useEffect(()=>{fetch('/api/connections',{cache:'no-store'}).then(async r=>{const d:any=await r.json();if(!r.ok||d.error)throw Error(d.error||'Connection unavailable');setConnections(d.connections||[]);}).catch(e=>setError(e.message));},[]);
 const caption=article.title+'\n\n'+article.body;
 const photos:string[]=article.media_json?JSON.parse(article.media_json).map((p:any)=>p.rendered):article.image?[article.image.replace(/\.png$/,'.jpg')]:[];
 const names:Record<string,string>={hub:'Hub website',facebook_organic:'Facebook',instagram:'Instagram'};
 function available(c:string){if(c==='hub')return article.status!=='published';const a=connections.find(x=>x.channel===c);return !!a?.connected&&!!a.actionAvailable&&(c!=='instagram'||caption.length<=2200);}
 async function publish(){if(running.current||!selected.length)return;const channels=selected.filter(available).sort((a,b)=>Number(a==='hub')-Number(b==='hub'));if(!channels.length)return;if(!confirm(`Publish this approved text and image to ${channels.map(c=>names[c]).join(', ')} now?${repost?' Reposting creates a new public copy.':''}`))return;
  running.current=true;setBusy(true);onBusy?.(true);setError('');setResults({});
  for(const channel of channels){try{const body=channel==='hub'?{id:article.id,revision:article.revision,action:'publish',channel:'hub'}:{id:article.id,revision:article.revision,channel,attemptId:crypto.randomUUID(),repost};
   const r=await fetch(channel==='hub'?'/api/articles':'/api/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok){setResults(old=>({...old,[channel]:{ok:false,message:d.error||'Publication failed',code:d.code,details:d.details,attempt:d.attempt}}));continue;}
   setResults(old=>({...old,[channel]:{ok:true,message:channel==='hub'?'Published on the Hub':d.receipt||'Published',url:channel==='hub'?d.article.published_url:d.postUrl}}));
  }catch(e){setResults(old=>({...old,[channel]:{ok:false,message:(e as Error).message}}));}}
  running.current=false;setBusy(false);onBusy?.(false);onDone();
 }
 async function resolveAttempt(channel:string,id:string){
  if(running.current||!confirm('Confirm you checked the platform and this attempt did not publish. This unlocks retry; it does not publish.'))return;
  running.current=true;setBusy(true);onBusy?.(true);
  try{const response=await fetch('/api/social',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'resolve',outcome:'not_published',confirmed:true})});const data:any=await response.json();if(!response.ok)throw Error(data.error);setResults(old=>({...old,[channel]:{ok:false,message:'Retry unlocked. Select Publish selected destinations when ready.'}}));onDone();}catch(e){setError((e as Error).message);}finally{running.current=false;setBusy(false);onBusy?.(false);}
 }
 return <section className="publisher"><p>Select destinations. Each gets a separate result; a failure on one does not undo another.</p><p className="notice">Facebook: Windsor has confirmed a publishing-permission issue awaiting Meta. You can prepare posts here; Facebook delivery remains unverified until Windsor confirms its fix.</p>{error&&<p role="alert" className="alert">{error}</p>}
 <fieldset disabled={busy}><legend>Publish to</legend>{['facebook_organic','instagram','hub'].map(c=><label className="check-row" key={c}><input type="checkbox" disabled={!available(c)} checked={selected.includes(c)} onChange={e=>setSelected(old=>e.target.checked?[...old,c]:old.filter(x=>x!==c))}/><span>{names[c]}{connections.find(x=>x.channel===c)?.publishingIssue?' · Last publishing attempt rejected':''}{!available(c)?c==='hub'?' · Already on Hub':c==='instagram'&&caption.length>2200?' · Caption too long':' · Connection unavailable':''}</span></label>)}<label className="check-row"><input type="checkbox" disabled/>X · No publishing action available</label><label className="check-row"><input type="checkbox" disabled/>vinconnect.com.au · Website integration required</label></fieldset>
 <p>{caption.length} characters · Instagram limit 2,200. Hub website is separate from vinconnect.com.au.</p>
 <p>{photos.length>1?`${photos.length} photos: Instagram publishes a carousel; Facebook uses the cover photo; the Hub displays the full gallery.`:"One branded photo will accompany the caption."}</p><details><summary>Preview approved caption and images</summary>{photos.map((src,i)=><img key={src+i} className="review-image" src={src} alt={`${article.title} — photo ${i+1}`}/>)}<p className="caption-preview">{caption}</p></details>
 <label className="check-row"><input type="checkbox" checked={repost} disabled={busy} onChange={e=>setRepost(e.target.checked)}/>Allow a new copy on platforms where this article was already published</label>
 <button className="primary" disabled={busy||!selected.some(available)} onClick={publish}>{busy?'Publishing selected destinations…':'Publish selected destinations'}</button>
 {Object.entries(results).map(([c,r])=><div className={r.ok?'notice':'alert'} role="status" key={c}><strong>{names[c]}: {r.ok?'Published':r.code==='FACEBOOK_PERMISSION_DENIED'?'Not published — permission denied':'Needs attention'}</strong><p>{r.message}</p>{r.details&&<details><summary>Technical details for Windsor support</summary><p className="caption-preview">{r.details}</p><p>Page: Vinconnect Starlink Solutions (1053341001203753). Facebook reauthorisation completed successfully, but publishing is still rejected. Please check pages_manage_posts, the Page token grants and your Meta app approval.</p></details>}{r.code==='FACEBOOK_PERMISSION_DENIED'&&<a href="https://onboard.windsor.ai/app/facebook_organic" target="_blank" rel="noreferrer">Open Windsor — use its support chat if reconnecting did not help ↗</a>}{r.attempt&&<button disabled={busy} onClick={()=>resolveAttempt(c,r.attempt!.id)}>I checked: this attempt did not publish; clear retry block</button>}{r.url&&<a href={r.url} target="_blank" rel="noreferrer">View post ↗</a>}</div>)}
 </section>;
}
type HistoryRow={id:string;article_id:string;title:string;channel:string;status:string;receipt:string;updated_at:string;post_url:string|null;provider_id:string|null;caption:string|null;image_url:string|null};
export function SocialHistory({refreshKey}:{refreshKey:number}){
 const [rows,setRows]=useState<HistoryRow[]>([]),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<HistoryRow|null>(null),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(0);
 useEffect(()=>{fetch('/api/social',{cache:'no-store'}).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);setRows(d.publications);setError('');}).catch(e=>setError(e.message));},[refreshKey,tick]);
 async function update(action:string,outcome?:string){if(!selected)return;if(action==='removed'&&!confirm('Confirm you have already deleted this post on the platform. This updates the Hub record only.'))return;if(outcome&&!confirm(`Confirm you checked the platform: this attempt ${outcome==='published'?'was published':'did not publish'}.`))return;setBusy(true);setError('');try{const r=await fetch('/api/social',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,action,outcome,confirmed:true,postUrl:url})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setSelected(null);setTick(t=>t+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const shown=rows.filter(r=>(filter==='all'||r.status===filter)&&[r.title,r.channel,r.receipt].join(' ').toLowerCase().includes(query.toLowerCase()));
 function exportCsv(){const values=[['Article','Platform','Status','Post link','Updated'],...shown.map(r=>[r.title||r.article_id,r.channel,r.status,r.post_url||'',r.updated_at])];const csv=values.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'"+'$&').replaceAll('"','""')+'"').join(',')).join('\r\n');const blob=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=blob;a.download='vinconnect-publishing-history.csv';a.click();setTimeout(()=>URL.revokeObjectURL(blob),1000);}
 return <section className="brand-panel history"><h2>Social publishing history</h2><div className="history-stats"><span>Published: {rows.filter(r=>r.status==='published').length}</span><span>Needs review: {rows.filter(r=>['sending','needs_review'].includes(r.status)).length}</span><span>Not published: {rows.filter(r=>r.status==='failed').length}</span></div>
 <div className="history-tools"><input aria-label="Search publishing history" placeholder="Search posts or platforms" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter publication status" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','published','sending','needs_review','failed','removed'].map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>setTick(t=>t+1)}>Refresh history</button><button onClick={exportCsv}>Export CSV</button></div>
 {error&&!selected&&<p role="alert" className="alert">{error}</p>}{!shown.length&&!error&&<p>No publications match this view.</p>}{shown.map(r=><article className="history-item" key={r.id}><strong>{r.title||r.article_id}</strong><p>{r.channel==='instagram'?'Instagram':'Facebook'} · {r.status} · {new Date(r.updated_at).toLocaleString()}</p>{r.post_url&&<a href={r.post_url} target="_blank" rel="noreferrer">View post ↗</a>}<button onClick={()=>{setSelected(r);setUrl(r.post_url||'');setError('');}}>Details & manage</button></article>)}
 <Dialog open={!!selected} onOpenChange={o=>{if(!o&&!busy)setSelected(null);}}><DialogContent className="review-modal"><DialogTitle>Publication details</DialogTitle><DialogDescription>Published posts are managed on their platform. The Windsor connector does not offer post editing or deletion.</DialogDescription>{selected&&<><h3>{selected.title||selected.article_id}</h3><p>{selected.channel} · {selected.status}</p>{selected.image_url&&<img className="review-image" src={selected.image_url} alt="Published image"/>}<p className="caption-preview">{selected.caption}</p><details><summary>Provider receipt</summary><p className="caption-preview">{selected.receipt}</p><p>Post ID: {selected.provider_id||'Not supplied'}</p></details><a className="primary" href={selected.post_url||(selected.channel==='instagram'?'https://www.instagram.com/vinconnectsolutions/':'https://www.facebook.com/1053341001203753')} target="_blank" rel="noreferrer">Open platform to view, edit or delete ↗</a><label>Direct link to this post<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><button disabled={busy||!url} onClick={()=>update('link')}>Save post link</button>{selected.status==='published'&&<button disabled={busy} onClick={()=>update('removed')}>I deleted it on the platform: mark removed</button>}{['sending','needs_review'].includes(selected.status)&&<><p>Check the platform before resolving an uncertain attempt. This changes the Hub record only.</p><button disabled={busy||!url} onClick={()=>update('resolve','published')}>I checked: published at this link</button><button disabled={busy} onClick={()=>update('resolve','not_published')}>I checked: not published; allow retry</button></>}{error&&<p role="alert" className="alert">{error}</p>}</>}</DialogContent></Dialog></section>;
}
