// A curated first collection: three clearly different designs per post category.
export const signatureDesigns=[
 {id:'signature-horizon',name:'Horizon / Installation',category:'Installations',scene:'cinema',palette:'carbon',font:'VinDisplay',format:'portrait',label:'FROM THE FIELD',headline:'COUNTRY LIFE. CONNECTED.',service:'Starlink installation',suburb:'Nyora',features:'Mount selection\nCable routing\nRouter setup',badge:'EXPLORE THE INSTALL',photo:3},
 {id:'signature-crafted',name:'Crafted / Installation',category:'Installations',scene:'folio',palette:'alpine',font:'VinDisplay',format:'square',label:'THE INSTALLATION EDIT',headline:'IT’S ALL IN THE FINISH.',service:'Installation details',suburb:'Cranbourne',features:'Position\nProtection\nPresentation',badge:'ON THE TOOLS',photo:1},
 {id:'signature-jobstory',name:'Job Story / Installation',category:'Installations',scene:'gallery',palette:'ocean',font:'VinHeadline',format:'landscape',label:'PROPERTY JOURNAL',headline:'ONE PROPERTY. EVERY DETAIL.',service:'Whole-property connectivity',suburb:'South Gippsland',features:'The brief\nThe installation\nThe handover',badge:'PROJECT NOTES',photo:4},
 {id:'signature-explainer',name:'The Explainer / Information',category:'Information & blogs',scene:'index',palette:'alpine',font:'VinDisplay',format:'portrait',label:'VINCONNECT FIELD GUIDE',headline:'GOOD WI-FI STARTS HERE.',service:'Router placement explained',suburb:'',features:'Find a central position\nConsider the building materials\nTest the spaces you use',badge:'PRACTICAL ADVICE',photo:14},
 {id:'signature-signal',name:'Signal / Information',category:'Information & blogs',scene:'broadcast',palette:'electric',font:'VinDisplay',format:'square',label:'THE BIG QUESTION',headline:'IS YOUR NETWORK READY?',service:'Backup power planning',suburb:'',features:'Identify essential devices\nCheck power requirements\nPlan the backup',badge:'READ THE GUIDE',photo:7},
 {id:'signature-perspective',name:'Perspective / Information',category:'Information & blogs',scene:'headline',palette:'alpine',font:'VinHeadline',format:'landscape',label:'A CLEARER PICTURE',headline:'WI-FI IS ONLY PART OF THE STORY.',service:'Understanding your connection',suburb:'',features:'Internet service\nLocal network\nDevice coverage',badge:'CONNECTIVITY EXPLAINED',photo:12},
 {id:'signature-people',name:'People First / Community',category:'Company & community',scene:'folio',palette:'alpine',font:'VinHeadline',format:'portrait',label:'BEHIND THE CONNECTION',headline:'LOCAL PEOPLE. PRACTICAL IDEAS.',service:'Meet VINCONNECT',suburb:'Our community',features:'People\nLocal knowledge\nPractical support',badge:'OUR STORY',photo:9},
 {id:'signature-gather',name:'Gather / Community',category:'Company & community',scene:'cinema',palette:'teal',font:'VinDisplay',format:'square',label:'RURAL CONNECTIONS',headline:'A PLACE TO CONNECT.',service:'Community conversations',suburb:'Rural Victoria',features:'Connect\nLearn\nShare',badge:'LET’S TALK',photo:11},
 {id:'signature-dispatch',name:'The Dispatch / Community',category:'Company & community',scene:'gallery',palette:'carbon',font:'VinHeadline',format:'landscape',label:'INSIDE VINCONNECT',headline:'THE WORK BEHIND THE CONNECTION.',service:'Team and project updates',suburb:'Out in the field',features:'Our people\nOur projects\nOur region',badge:'FROM THE TEAM',photo:8},
 {id:'signature-open-country',name:'Open Country / Marketing',category:'Marketing',scene:'cinema',palette:'field',font:'VinDisplay',format:'landscape',label:'BEYOND THE HOUSE',headline:'MORE SPACE. MORE POSSIBILITY.',service:'Rural property connectivity',suburb:'Coast to country',features:'House\nShed\nStable',badge:'PLAN YOUR PROPERTY',photo:3},
 {id:'signature-everyday',name:'Everyday / Marketing',category:'Marketing',scene:'headline',palette:'alpine',font:'VinDisplay',format:'square',label:'CONNECTED LIVING',headline:'MAKE ROOM FOR A BETTER CONNECTION.',service:'Home Wi-Fi planning',suburb:'',features:'Work\nHome\nEveryday life',badge:'EXPLORE THE OPTIONS',photo:2},
 {id:'signature-afterhours',name:'After Hours / Marketing',category:'Marketing',scene:'broadcast',palette:'carbon',font:'VinDisplay',format:'portrait',label:'SEE THE BIGGER PICTURE',headline:'YOUR PROPERTY. IN VIEW.',service:'CCTV and remote monitoring',suburb:'',features:'Camera coverage\nLocal recording\nRemote viewing',badge:'PLAN YOUR COVERAGE',photo:5},
 {id:'signature-local',name:'Local Connection / Advertising',category:'Advertising',scene:'folio',palette:'alpine',font:'VinDisplay',format:'portrait',label:'YOUR LOCAL VINCONNECT',headline:'A BETTER CONNECTION STARTS HERE.',service:'Starlink installation enquiries',suburb:'Nyora · Lang Lang · Poowong',features:'Starlink\nWi-Fi\nCCTV',badge:'REQUEST A QUOTE',photo:4},
 {id:'signature-switch',name:'Make the Switch / Advertising',category:'Advertising',scene:'broadcast',palette:'teal',font:'VinDisplay',format:'square',label:'LET’S GET CONNECTED',headline:'GIVE YOUR CONNECTION A NEW DIRECTION.',service:'Starlink and Wi-Fi installation',suburb:'',features:'Discuss the property\nReview the options\nConfirm the scope',badge:'CALL VINCONNECT',photo:1},
 {id:'signature-nextstep',name:'Next Step / Advertising',category:'Advertising',scene:'index',palette:'alpine',font:'VinHeadline',format:'landscape',label:'START WITH A CONVERSATION',headline:'YOUR PLACE. A PRACTICAL PLAN.',service:'Property network enquiries',suburb:'',features:'Tell us what you need\nMap the connection\nGet a scoped quote',badge:'LET’S MAKE A PLAN',photo:3},
] as const;
export const signatureIds=new Set<string>(signatureDesigns.map(d=>d.id));
export const signaturePhotos:Record<string,string>={
 'signature-horizon':'/assets/signature/rural-life.webp',
 'signature-open-country':'/assets/signature/property-network.webp',
 'signature-afterhours':'/assets/signature/home-security.webp',
 'signature-gather':'/assets/signature/community-hub.webp',
};
