import {signatureDesigns} from './signature-templates';
export const collectionPalettes={
 ocean:{bg:'#082b3c',fg:'#ffffff',accent:'#36c7eb',soft:'#154356',light:false},
 alpine:{bg:'#f5f8f6',fg:'#142f34',accent:'#007f88',soft:'#dcebea',light:true},
 dusk:{bg:'#1d2931',fg:'#ffffff',accent:'#f3c566',soft:'#34444b',light:false},
 electric:{bg:'#071c35',fg:'#ffffff',accent:'#35bcff',soft:'#103a62',light:false},
 field:{bg:'#142b2b',fg:'#ffffff',accent:'#b7db58',soft:'#29443e',light:false},
 sand:{bg:'#faf4e9',fg:'#253532',accent:'#90631f',soft:'#e9dfcc',light:true},
 teal:{bg:'#073d43',fg:'#ffffff',accent:'#66dfcf',soft:'#10545a',light:false},
 carbon:{bg:'#20272b',fg:'#ffffff',accent:'#00c3ca',soft:'#38484e',light:false},
} as const;
// New designs keep the existing original logo colours. Secondary accent palettes
// follow supplied campaign references; all factual copy comes from post fields.
export const collectionDesigns=[
 ...signatureDesigns,
 {id:'coastal-install',name:'Coastal Connection',category:'Installations',scene:'panorama',palette:'ocean',font:'VinDisplay',format:'square',label:'ON THE COAST',headline:'A FRESH CONNECTION',service:'Starlink installation',suburb:'Wonthaggi',features:'Roof mounting\nCable routing\nRouter setup',badge:'INSTALL SPOTLIGHT',photo:5},
 {id:'field-notes',name:'Field Notes',category:'Installations',scene:'dossier',palette:'alpine',font:'VinHeadline',format:'portrait',label:'FROM THE JOB FILE',headline:'THE DETAILS MAKE THE DIFFERENCE',service:'Installation journal',suburb:'Nyora',features:'Site planning\nMount selection\nCable finish',badge:'ON THE TOOLS',photo:4},
 {id:'clubhouse',name:'Clubhouse Connected',category:'Installations',scene:'mosaic',palette:'carbon',font:'VinDisplay',format:'landscape',label:'PROJECT SPOTLIGHT',headline:'READY FOR GAME DAY',service:'Club connectivity',suburb:'Cranbourne',features:'Starlink installation\nNetwork cabling\nWi-Fi planning',badge:'PROJECT GALLERY',photo:8},
 {id:'precision',name:'Precision Finish',category:'Installations',scene:'diagonal',palette:'alpine',font:'VinDisplay',format:'square',label:'INSTALLATION DETAIL',headline:'PLANNED. FITTED. CONNECTED.',service:'Starlink installation',suburb:'Botanic Ridge',features:'Mount placement\nInternal cabling\nEquipment setup',badge:'THE FINISH MATTERS',photo:1},
 {id:'homestead',name:'Homestead Journal',category:'Installations',scene:'postcard',palette:'dusk',font:'VinDisplay',format:'portrait',label:'COUNTRY CONNECTIONS',headline:'A CONNECTION FOR COUNTRY LIFE',service:'Rural installation',suburb:'Poowong',features:'House connection\nShed link planning\nWi-Fi placement',badge:'LOCAL INSTALL',photo:3},
 {id:'storm-watch',name:'Storm Watch',category:'Information & blogs',scene:'question',palette:'electric',font:'VinDisplay',format:'landscape',label:'THE PRACTICAL QUESTION',headline:'WHAT HAPPENS WHEN THE POWER GOES OUT?',service:'Backup power planning',suburb:'',features:'Power requirements\nBackup options\nEquipment checks',badge:'PLAN AHEAD',photo:7},
 {id:'signal-school',name:'Signal School',category:'Information & blogs',scene:'guide',palette:'alpine',font:'VinHeadline',format:'portrait',label:'THE WI-FI GUIDE',headline:'GIVE YOUR ROUTER A BETTER HOME',service:'Router placement',suburb:'',features:'Choose the location\nPlan cable access\nCheck coverage',badge:'READ THE GUIDE',photo:14},
 {id:'water-wise',name:'Water Wise',category:'Information & blogs',scene:'panorama',palette:'field',font:'VinHeadline',format:'landscape',label:'RURAL TECH EXPLAINED',headline:'KEEP AN EYE ON YOUR WATER',service:'Remote monitoring explained',suburb:'Country living',features:'Sensor options\nNetwork requirements\nRemote access',badge:'HOW IT WORKS',photo:3},
 {id:'myth-check',name:'Myth Check',category:'Information & blogs',scene:'cards',palette:'electric',font:'VinDisplay',format:'square',label:'LOOK A LITTLE CLOSER',headline:'ONE ROUTER FOR EVERY ROOM?',service:'Understanding Wi-Fi coverage',suburb:'',features:'Building materials\nRouter position\nMesh options',badge:'LET’S EXPLAIN',photo:2},
 {id:'deep-dive',name:'The Deep Dive',category:'Information & blogs',scene:'editorial',palette:'sand',font:'VinDisplay',format:'landscape',label:'VINCONNECT EXPLAINS',headline:'MORE THAN ONE INTERNET CONNECTION',service:'Bonding and failover',suburb:'',features:'Different approaches\nEquipment choices\nPlanning the setup',badge:'TECH EXPLAINED',photo:12},
 {id:'local-roots',name:'Local Roots',category:'Company & community',scene:'postcard',palette:'sand',font:'VinHeadline',format:'square',label:'PART OF THE COMMUNITY',headline:'LOCAL PEOPLE. LOCAL CONNECTIONS.',service:'The VINCONNECT story',suburb:'South Gippsland',features:'Our area\nOur work\nOur story',badge:'HELLO FROM VINCONNECT',photo:11},
 {id:'crew-diary',name:'Crew Diary',category:'Company & community',scene:'mosaic',palette:'alpine',font:'VinDisplay',format:'portrait',label:'BEHIND THE SCENES',headline:'A DAY ON THE TOOLS',service:'Behind the installation',suburb:'Out and about',features:'The site visit\nThe setup\nThe finishing details',badge:'FROM THE FIELD',photo:8},
 {id:'community-pulse',name:'Community Pulse',category:'Company & community',scene:'ribbon',palette:'teal',font:'VinHeadline',format:'landscape',label:'STRONGER LOCAL CONNECTIONS',headline:'GOOD THINGS HAPPEN TOGETHER',service:'Community stories',suburb:'Our local area',features:'People\nPlaces\nProjects',badge:'IN OUR COMMUNITY',photo:9},
 {id:'milestone',name:'The Milestone',category:'Company & community',scene:'poster',palette:'dusk',font:'VinDisplay',format:'square',label:'A MOMENT TO SHARE',headline:'ANOTHER CHAPTER FOR VINCONNECT',service:'Company news',suburb:'Thank you',features:'Latest news\nTeam updates\nWhat comes next',badge:'VINCONNECT UPDATE',photo:6},
 {id:'inside-vinconnect',name:'Inside VINCONNECT',category:'Company & community',scene:'editorial',palette:'alpine',font:'VinHeadline',format:'portrait',label:'MEET THE BUSINESS',headline:'THE PEOPLE BEHIND THE CONNECTION',service:'About VINCONNECT',suburb:'Our story',features:'Our approach\nOur local focus\nOur projects',badge:'BEHIND THE BRAND',photo:9},
 {id:'beyond-fence',name:'Beyond the Fence',category:'Marketing',scene:'panorama',palette:'field',font:'VinDisplay',format:'square',label:'THINK BEYOND THE HOUSE',headline:'BIG PROPERTY. BIG POSSIBILITIES.',service:'Property connectivity',suburb:'Rural Victoria',features:'Shed links\nWi-Fi planning\nOutdoor connections',badge:'EXPLORE YOUR OPTIONS',photo:3},
 {id:'coast-country',name:'Coast & Country',category:'Marketing',scene:'postcard',palette:'ocean',font:'VinDisplay',format:'landscape',label:'WHERE YOU CALL HOME',headline:'YOUR PLACE. YOUR CONNECTION.',service:'Starlink & property Wi-Fi',suburb:'Coast to country',features:'Homes\nLifestyle properties\nLocal businesses',badge:'LET’S TALK',photo:11},
 {id:'connected-living',name:'Connected Living',category:'Marketing',scene:'diagonal',palette:'sand',font:'VinHeadline',format:'portrait',label:'MAKE ROOM FOR MORE',headline:'WORK. PLAY. CONNECT.',service:'Home network planning',suburb:'Life at home',features:'Home office\nLiving spaces\nOutbuildings',badge:'PLAN YOUR SPACE',photo:2},
 {id:'after-dark',name:'After Dark',category:'Marketing',scene:'ribbon',palette:'electric',font:'VinDisplay',format:'square',label:'A DIFFERENT KIND OF CONNECTION',headline:'BRING YOUR NEXT IDEA ONLINE',service:'Connectivity possibilities',suburb:'Think bigger',features:'Starlink\nWi-Fi\nData cabling',badge:'WHAT’S YOUR NEXT PROJECT?',photo:12},
 {id:'possibility-map',name:'Possibility Map',category:'Marketing',scene:'cards',palette:'teal',font:'VinHeadline',format:'landscape',label:'START WITH A PLAN',headline:'ONE PROPERTY. MANY POSSIBILITIES.',service:'A connected property',suburb:'',features:'The home\nThe shed\nThe workspace',badge:'EXPLORE THE OPTIONS',photo:10},
 {id:'electric-launch',name:'Electric Launch',category:'Advertising',scene:'question',palette:'electric',font:'VinDisplay',format:'portrait',label:'READY FOR A CHANGE?',headline:'LET’S TALK ABOUT YOUR INTERNET',service:'Starlink installation enquiries',suburb:'',features:'Talk through the job\nReview the options\nPlan the installation',badge:'ASK VINCONNECT',photo:1},
 {id:'local-legend',name:'Local Legend',category:'Advertising',scene:'poster',palette:'ocean',font:'VinHeadline',format:'square',label:'YOUR LOCAL CONNECTION',headline:'STARLINK INSTALLATIONS',service:'Installation enquiries',suburb:'Nyora',features:'Nyora\nLang Lang\nPoowong',badge:'MESSAGE US',photo:3},
 {id:'clean-line',name:'Clean Line',category:'Advertising',scene:'editorial',palette:'alpine',font:'VinDisplay',format:'landscape',label:'LET’S MAKE A PLAN',headline:'A CLEAR PATH TO CONNECTION',service:'Starlink & Wi-Fi',suburb:'',features:'Homes\nSheds\nWorkspaces',badge:'GET IN TOUCH',photo:14},
 {id:'service-focus',name:'Service Focus',category:'Advertising',scene:'dossier',palette:'carbon',font:'VinHeadline',format:'portrait',label:'VINCONNECT SERVICES',headline:'PUT YOUR PROPERTY ON THE MAP',service:'Property network planning',suburb:'Your place',features:'Starlink installations\nWi-Fi links\nData cabling',badge:'TALK TO THE TEAM',photo:5},
 {id:'bold-move',name:'The Bold Move',category:'Advertising',scene:'diagonal',palette:'dusk',font:'VinDisplay',format:'square',label:'YOUR NEXT CONNECTION',headline:'MAKE YOUR NEXT MOVE CONNECTED',service:'Installation enquiries',suburb:'',features:'Site planning\nMounting options\nNetwork setup',badge:'CALL VINCONNECT',photo:4},
] as const;
export const collectionById=new Map<string,typeof collectionDesigns[number]>(collectionDesigns.map(d=>[d.id,d]));
